kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "poc1-producer"
spec:
  source:
    git:
      uri: "https://github.com/Dimss/poc1.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "DOCKER_REGISTRY"
        value: "docker.io"
    type: JenkinsPipeline