kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "poc1-producer"
spec:
  source:
    git:
      uri: "https://gitlab.com/dimss/poc1-producer.git"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "GOVIL_APP_NAME"
        value: "poc1-producer"
      - name: "S2I_BUILD_IMAGE"
        value: "python:3.6"
      - name: "DOCKER_IMAGE_PREFIX"
        value: "dimssss"
      - name: "DOCKER_REGISTRY"
        value: "docker.io"
      - name: "gitlabBranch"

    type: JenkinsPipeline
  triggers:
#  - gitlab:
#      secret: YGFThSmhjrYdAjGeAVw4
#    type: "GitLab"
  - generic:
      allowEnv: true
      secret: YGFThSmhjrYdAjGeAVw4
    type: Generic

#  - github:
#      secret: YGFThSmhjrYdAjGeAVw4
#    type: GitHub