apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: Poc1Producer
message: |-
  Poc1Producer Custom Resource Template
metadata:
  name: poc1producer-cr
  annotations:
    description: |-
      Poc1Producer Custom Resource Template
    iconClass: fa fa-mixcloud
    openshift.io/display-name: Poc1Producer
    openshift.io/provider-display-name: GovIL-Poc1Producer by RH PS
    tags: cr
objects:
- apiVersion: gov.il/v1alpha1
  kind: Poc1Producer
  metadata:
    name: ${SERVICE_NAME}
    labels:
      profile: ${PROFILE}
  spec:
    size: ${SIZE}
    depOwner: poc12
    appName: ${SERVICE_NAME}
    image: ${IMAGE}
    profile: ${PROFILE}
    namespace: ${NAMESPACE}
parameters:
- description: Count of instaces
  displayName: How many instaces should be deployed
  name: SIZE
  value: "1"
  required: true
- description: Name of the Poc1Producer instace
  displayName: This name will be used by all objects created by CR (pods,services,deployments, etc..)
  name: ROUTE_NAME
  required: true
- description: Route name
  displayName: Name of the OpenShift route object
  name: NAMESPACE
  required: true
  value: govil
- description: Poc1Producer image
  displayName: Poc1Producer Docker image
  name: IMAGE
  required: true
- description: Container port
  displayName: Port number that should be exposed from container
  name: PORT
  required: true
- description: Poc1Producer Profile
  displayName: Poc1Producer profile  #dev/lab/prod
  name: PROFILE
  value: dev
  required: true
